// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWC2zMHfxZflOV3jYkv5-mfAD4eJwlsEk',
    appId: '1:689572458905:web:06e403218d3ec79c74e308',
    messagingSenderId: '689572458905',
    projectId: 'gloriaapp-2a653',
    authDomain: 'gloriaapp-2a653.firebaseapp.com',
    storageBucket: 'gloriaapp-2a653.firebasestorage.app',
    measurementId: 'G-VTB0EGC37K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbr_1oKtrJvjIol960j6ZZMu7gysNXd38',
    appId: '1:689572458905:android:91f9742df05274d174e308',
    messagingSenderId: '689572458905',
    projectId: 'gloriaapp-2a653',
    storageBucket: 'gloriaapp-2a653.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi-tjheO_753LC188rvcB6FksWPubqzCQ',
    appId: '1:689572458905:ios:bc338542fcd43f0e74e308',
    messagingSenderId: '689572458905',
    projectId: 'gloriaapp-2a653',
    storageBucket: 'gloriaapp-2a653.firebasestorage.app',
    iosBundleId: 'com.example.gloriaapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCi-tjheO_753LC188rvcB6FksWPubqzCQ',
    appId: '1:689572458905:ios:bc338542fcd43f0e74e308',
    messagingSenderId: '689572458905',
    projectId: 'gloriaapp-2a653',
    storageBucket: 'gloriaapp-2a653.firebasestorage.app',
    iosBundleId: 'com.example.gloriaapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWC2zMHfxZflOV3jYkv5-mfAD4eJwlsEk',
    appId: '1:689572458905:web:d39e4b4f69a79dbf74e308',
    messagingSenderId: '689572458905',
    projectId: 'gloriaapp-2a653',
    authDomain: 'gloriaapp-2a653.firebaseapp.com',
    storageBucket: 'gloriaapp-2a653.firebasestorage.app',
    measurementId: 'G-10XKPH6K16',
  );

}